# Generated by Django 4.2.20 on 2025-04-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comidas',
            fields=[
                ('id_comida', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('peso', models.FloatField()),
                ('graxas', models.FloatField()),
                ('carbohidratos', models.FloatField()),
                ('proteinas', models.FloatField()),
                ('calorias', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercicios',
            fields=[
                ('id_exercicio', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('repeticions', models.CharField(max_length=10)),
                ('peso', models.FloatField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UpLife_api.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('nome_usuario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('imaxe_perfil', models.ImageField(blank=True, null=True, upload_to='media')),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('peso', models.IntegerField(blank=True, null=True)),
                ('obxectivo', models.CharField(blank=True, max_length=20, null=True)),
                ('actividade', models.CharField(blank=True, max_length=20, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('calorias_diarias', models.IntegerField(blank=True, null=True)),
                ('auga_diaria', models.IntegerField(blank=True, null=True)),
                ('modo_aplicacion', models.CharField(choices=[('C', 'Claro'), ('E', 'Escuro')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id_tarefa', models.BigAutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
                ('titulo', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('completado', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UpLife_api.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Plantillas',
            fields=[
                ('id_plantilla', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('icona', models.ImageField(upload_to='media')),
                ('exercicios', models.ManyToManyField(to='UpLife_api.exercicios')),
            ],
        ),
        migrations.CreateModel(
            name='Medallas',
            fields=[
                ('id_medalla', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200, unique=True)),
                ('completado', models.BooleanField()),
                ('icona', models.ImageField(upload_to='media')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UpLife_api.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id_grupo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('icona', models.ImageField(upload_to='media')),
                ('comidas', models.ManyToManyField(to='UpLife_api.comidas')),
            ],
        ),
        migrations.AddField(
            model_name='exercicios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UpLife_api.usuarios'),
        ),
        migrations.AddField(
            model_name='comidas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UpLife_api.usuarios'),
        ),
        migrations.CreateModel(
            name='Auga',
            fields=[
                ('id_auga', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidade', models.IntegerField()),
                ('hora', models.TimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UpLife_api.usuarios')),
            ],
        ),
    ]
