# Generated by Django 4.2.20 on 2025-04-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='contraseña',
            new_name='contrasinal',
        ),
    ]
