# Generated by Django 4.2.20 on 2025-04-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0002_rename_contraseña_usuarios_contrasinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='nome_usuario',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
