# Generated by Django 4.2.20 on 2025-04-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0003_alter_usuarios_nome_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medallas',
            name='usuario',
        ),
    ]
