# Generated by Django 4.2.20 on 2025-04-22 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0004_remove_medallas_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='medallas',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='UpLife_api.usuarios'),
        ),
    ]
