# Generated by Django 4.2.20 on 2025-04-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0007_remove_medallas_usuario_medallas_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='actividade',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='obxectivo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
