# Generated by Django 4.2.20 on 2025-04-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0008_alter_usuarios_actividade_alter_usuarios_obxectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='xenero',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
