# Generated by Django 4.2.20 on 2025-04-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0009_usuarios_xenero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
