# Generated by Django 4.2.20 on 2025-04-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0010_alter_tarefas_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='auga',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comidas',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercicios',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
