# Generated by Django 4.2.20 on 2025-05-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0011_auga_data_comidas_data_exercicios_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillas',
            name='icona',
            field=models.CharField(max_length=255),
        ),
    ]
