# Generated by Django 4.2.20 on 2025-05-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0013_plantillas_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillas',
            name='exercicios',
            field=models.ManyToManyField(blank=True, null=True, to='UpLife_api.exercicios'),
        ),
    ]
