# Generated by Django 4.2.20 on 2025-05-05 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0014_alter_plantillas_exercicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillas',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UpLife_api.usuarios'),
        ),
    ]
