# Generated by Django 4.2.20 on 2025-05-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0016_alter_plantillas_exercicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillas',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
