# Generated by Django 4.2.20 on 2025-05-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0017_alter_plantillas_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillas',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
