# Generated by Django 4.2.20 on 2025-05-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0018_plantillas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='icona',
            field=models.CharField(max_length=255),
        ),
    ]
