# Generated by Django 4.2.21 on 2025-05-14 12:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0020_grupos_usuario'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='plantillas',
        #     name='data',
        # ),
        migrations.AddField(
            model_name='plantillas',
            name='datas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
    ]
