# Generated by Django 4.2.21 on 2025-05-14 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0020_grupos_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantillas',
            name='data',
        ),
        migrations.CreateModel(
            name='UsoPlantilla',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UpLife_api.plantillas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UpLife_api.usuarios')),
            ],
        ),
    ]
