# Generated by Django 4.2.21 on 2025-05-19 09:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0021_remove_plantillas_data_usoplantilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medallas',
            name='icona',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='imaxe_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
