# Generated by Django 4.2.21 on 2025-05-19 09:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0022_alter_medallas_icona_alter_usuarios_imaxe_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medallas',
            name='icona',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
