# Generated by Django 4.2.21 on 2025-05-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0023_alter_medallas_icona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medallas',
            name='icona',
            field=models.URLField(blank=True, null=True),
        ),
    ]
