# Generated by Django 4.2.21 on 2025-05-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpLife_api', '0025_alter_medallas_icona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillas',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
